export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const INIT_INGREDIENTS_FAILED = 'INIT_INGREDIENTS_FAILED'

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const LOADING_ORDERS = 'LOADING_ORDERS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'